owner: dlunch
repo: upptime
user-agent: dlunch

# Add your sites here
sites:
  - name: data
    url: $SECRET_SITE_1
  - name: data kr
    url: $SECRET_SITE_2

# Add downtime notifications
# https://upptime.js.org/docs/notifications
notifications:
assignees:

# Configure your status website
# http://localhost:3000/docs/configuration#status-website
status-website:
  cname: upptime.dlunch.net
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle:
  introMessage:
