owner: koj-co
repo: upptime
user-agent: KojBot

# Add your sites here
sites:
  - name: ffxiv-data 1
    url: $FFXIV_DATA_1
  - name: ffxiv-data 2
    url: $FFXIV_DATA_2

# Add downtime notifications
# https://upptime.js.org/docs/notifications
notifications:
assignees:

# Configure your status website
# http://localhost:3000/docs/configuration#status-website
status-website:
  cname: upptime.dlunch.net
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle:
  introMessage:
